### ISSUE TITLE
the prefab initializes to wrong data when scroll view is used in fast manner.

### ISSUE THREAD

**Issue by Uchiha1391** [disas69/Unity-Pooled-Scroll-List#2]
To create the issue. In the provided test scene setup the amount to 10 and the use the vertical Scroll List( as I am using that only)
is fast manner(move the list up/down fast) and you will see the wrong data initialized. If used again slowly then it reorients correctly. check the attached clip showing the problem below.

https://user-images.githubusercontent.com/28823508/111069596-ce6b7400-84f3-11eb-8fa6-f9fd552081c4.mp4

**Comment by disas69** [comment]
Hi,

Thanks for finding the issue! It is fixed now in version 1.1.

Regards,
Eugene
